README.md
packages/sdk/README.md
packages/sdk/src/core/core.ts

Add:
- define default web3 provider in sdk
- set web3 provder
Update:
- readme

feat: add define web3 provider, update readme

---

playground/package.json
yarn.lock

Fix:
- Playground dependencies

fix: playgraund reef-knote deps

---

.github/workflows/publish.yml

fix: fix publish

---

.github/workflows/publish.yml

Add provenance to publish ci
- https://docs.npmjs.com/generating-provenance-statements

feat: add provenance for publish

---

packages/sdk/src/common/decorators/ErrorHandler.ts
packages/sdk/src/staking/staking.ts

fix: fix errorHandler

---

.github/workflows/deploy-pages.yml
playground/package.json

Added github pages deploy workflow

feat: deploy workflow

---

packages/sdk/README.md
packages/sdk/package.json
packages/sdk/src/common/decorators/ErrorHandler.ts
packages/sdk/src/common/decorators/Initialize.ts
packages/sdk/src/common/decorators/cache.ts
packages/sdk/src/common/decorators/logger.ts
packages/sdk/src/common/decorators/utils.ts
packages/sdk/src/core/core.ts
packages/sdk/src/core/types.ts
packages/sdk/src/staking/staking.ts
playground/demo/core/index.tsx
playground/demo/withdrawals/claim.tsx
playground/providers/sdk.tsx
yarn.lock

Add:
- `logMode` for `sdk`
- license to package
- update `viem` version
- `balanceETH` for playground
- enable debug mode in playground

Log mode for console

---

packages/sdk/src/index.ts
packages/sdk/src/withdrawals/index.ts

Change export for withdrawals

---

.github/workflows/deploy-pages.yml
playground/package.json
playground/pages/_document.tsx

Fix playground deploy

---

.github/workflows/deploy-pages.yml

fix: pass base path as env

---

.github/workflows/deploy-pages.yml

Disable dynamics override by export

fix: no override dynamics on export

---

packages/sdk/src/common/decorators/cache.ts

Fix:
- bitInt cache
- cache for promise

fix: fix bigInt cache

---

.github/workflows/checks.yml
.github/workflows/deploy-pages.yml

Update envs for playground deploy

fix: update build envs

---

README.md
packages/sdk/README.md

docs: add badges

---

packages/sdk/src/core/index.ts
playground/components/action/action.tsx
playground/components/back-argument-input/index.tsx
playground/components/block-argument-input/index.tsx
playground/components/connection-error/index.tsx
playground/demo/events/index.tsx
playground/demo/rewards/index.tsx
playground/demo/rewards/rewards-table.tsx
playground/package.json
playground/pages/index.tsx
playground/utils/noop.ts
yarn.lock

- More controls/inputs
- Events and Rewards playground better UI
- React Json View for default

Playground improvement

---

packages/sdk/MIGRATION.md
packages/sdk/README.md
packages/sdk/src/common/utils/bigint-comparator.ts
packages/sdk/src/erc20/erc20.ts
packages/sdk/src/shares/__tests__/shares-wallet.test.ts
packages/sdk/src/shares/__tests__/shares.test.ts
packages/sdk/src/shares/abi/steth-shares-abi.ts
packages/sdk/src/shares/shares.ts
packages/sdk/src/stake/__tests__/stake.test.ts
packages/sdk/src/unsteth/unsteth.ts
packages/sdk/src/withdraw/claim/claim.ts
packages/sdk/src/wrap/__test__/wrap.test.ts
packages/sdk/tests/utils/expect/expect-sdk-module.ts
packages/sdk/tests/utils/fixtures/use-core.ts
packages/sdk/tests/utils/fixtures/use-shares.ts
packages/sdk/tests/utils/fixtures/use-steth.ts
packages/sdk/tests/utils/fixtures/use-wallet-client.ts
packages/sdk/tests/utils/fixtures/use-wsteth.ts
playground/demo/unsteth/index.tsx
playground/demo/withdrawals/claim.tsx
playground/demo/wrap/index.tsx

- fixed shares transfer method
- better account hoisting in erc20
- shares module tests

Shares fix & tests

---

packages/sdk/src/stake/__tests__/stake-wallet.test.ts
packages/sdk/src/withdraw/__test__/withdraw-claim.test.ts
packages/sdk/src/withdraw/__test__/withdraw-request-info.test.ts
packages/sdk/src/withdraw/__test__/withdraw-request.test.ts
packages/sdk/src/withdraw/__test__/withdraw-views.test.ts
packages/sdk/src/withdraw/__test__/withdraw.test.ts
packages/sdk/src/withdraw/claim/types.ts
packages/sdk/src/withdraw/index.ts
packages/sdk/src/withdraw/request/approve.ts
packages/sdk/src/withdraw/request/request.ts
packages/sdk/src/withdraw/types.ts
packages/sdk/src/withdraw/withdraw-requests-info.ts
packages/sdk/src/withdraw/withdraw-views.ts
packages/sdk/tests/utils/expect/expect-sdk-error.ts
packages/sdk/tests/utils/expect/expect-unique-array.ts
playground/providers/sdk.tsx

- minor account hoisting fix for withdraw request&approve
- types
- fix requests order in request info 
- fix claimable requests return unfinalized requests
- add error for passing unfinalized ids to `findCheckpointHints` 
- playground: add injected sdk instance for debug
Withdraw unit tests:

[unit tests] withdrawals

---

README.md
packages/sdk/CHANGELOG.md
packages/sdk/README.md

Added CHANGELOG.md
merged dependabot prs

docs: changelog

---

.github/workflows/checks.yml
.github/workflows/deploy-pages.yml
.github/workflows/publish.yml
LICENSE.txt
packages/sdk/LICENSE.txt
packages/sdk/jest.config.ts
packages/sdk/package.json
playground/components/back-argument-input/index.tsx
playground/components/block-argument-input/index.tsx
playground/components/custom-rpc-input/custom-rpc-input.tsx
playground/pages/_document.tsx
yarn.lock

**SDK was rebuild and verified to have NO changes to packaged code.** 
No changes to SDK code, nothing to test

[Build] Node 20 and workflow update 

---

.github/workflows/publish-alpha.yml
.github/workflows/publish.yml
package.json
yarn.lock

Updates actions config to enable provenance attestation.

[build]fix provenance config

---

README.md
examples/Examples.md
examples/rewards/README.md

Change wording to be more specific about details and disambiguate collective accounts widely used for CEX/custodian services.

Doc: suggest some minor edits for reward examples

---

README.md

Made badges in readme clickable links

docs: add links in readme

---

README.md

docs: fix examples link

---

examples/README.md

fix: readme anchor link

---

.github/workflows/publish-alpha.yml
.github/workflows/publish-dry-run.yml
.github/workflows/publish.yml
package.json
packages/sdk/src/stake/stake.ts

[Build] add pre publish

---

packages/sdk/CHANGELOG.md
packages/sdk/src/rewards/__tests__/__snapshots__/rewards.test.ts.snap
packages/sdk/src/rewards/rewards.ts
packages/sdk/src/statistics/__tests__/stats.test.ts
packages/sdk/src/statistics/apr.ts

apr percent in rewards

---

.github/workflows/checks.yml
packages/sdk/src/common/constants.ts
packages/sdk/src/core/core.ts
packages/sdk/src/l2/__test__/l2.test.ts
packages/sdk/src/l2/l2.ts
packages/sdk/src/l2/tokens.ts
packages/sdk/src/rewards/rewards.ts
packages/sdk/src/withdraw/withdraw-waiting-time.ts
packages/sdk/tests/global-setup.cjs
packages/sdk/tests/global-teardown.cjs
packages/sdk/tests/utils/expect/expect-erc20-wallet.ts
packages/sdk/tests/utils/expect/expect-erc20.ts
packages/sdk/tests/utils/fixtures/use-l2.ts
packages/sdk/tests/utils/fixtures/use-test-envs.ts

- fixed permit for l2 tokens
- added `isSupportedOnChain` helper for l2 module
- l2 test suit
- minor types adjustments

Extra tests for l2 module

---

packages/sdk/src/l2/l2.ts

fix: add decorator

---

docs/sdk/intro.md
packages/sdk/CHANGELOG.md

Breaking change commit for v3.5.0

---

packages/sdk/CHANGELOG.md

docs: set right version in changelog

---

docs/sdk/intro.md
packages/sdk/CHANGELOG.md
yarn.lock

Update docs 

---

packages/sdk/CHANGELOG.md
packages/sdk/src/rewards/rewards.ts

fix: self transfer edge case

---

packages/sdk/src/core/index.ts

fix: export lido locator abi

---

packages/sdk/src/erc20/erc20.ts
packages/sdk/src/l2/l2.ts
packages/sdk/tests/utils/expect/expect-erc20-wallet.ts

feat: estimate approve for erc20

---

packages/sdk/src/common/constants.ts
packages/sdk/src/common/utils/sdk-error.ts

fix: remove const enum

---

README.md
docs/sdk/intro.md
packages/sdk/README.md

docs: remove wip

---

docs/sdk/modules/l2.md
packages/sdk/CHANGELOG.md

Unichain – update changelog, add to docs

---

playground/env-dynamics.mjs
playground/providers/web3.tsx

* [`playground/env-dynamics.mjs`](diffhunk://#diff-5b9b16ab1698e0e365ea237b561c504e93cc5bf1021491bbbba65bb3ecef2d70L12-R12): Updated the comment for the Unichain network to "Unichain Sepolia" in the `rpcProviderUrls` object.
* [`playground/providers/web3.tsx`](diffhunk://#diff-b9244967eedbb4b94c33a3f8b0371c164cf0360b534fb17dc1c61bb895c6fbaaL71-R71): Updated the comment for the Unichain network to "Unichain Sepolia" in the `Web3Provider` component.

Fix Unichain comments

---

packages/sdk/src/common/chains/index.ts
packages/sdk/src/common/index.ts

fix: export unichain definition

---

packages/sdk/src/core/core.ts
packages/sdk/src/core/types.ts

(WIP) Feature/prepare to devnet

---

packages/sdk/src/core/core.ts

This pull request makes updates to the `LidoSDKCore` class in `packages/sdk/src/core/core.ts`, including fixing a typo in an error message and enhancing the `isContract` method to improve contract detection logic.
* Corrected a typo in the error message for unsupported chains by changing "Contacts" to "Contracts." (`packages/sdk/src/core/core.ts`, [packages/sdk/src/core/core.tsL190-R190](diffhunk://#diff-6567a6e87f732d8adba506bcea3ebf1f8e4a88cf38420948dd5007c21d7ae4c6L190-R190))
* Updated the `isContract` method to improve the logic for identifying contracts. It now checks for both regular accounts (EOA) and delegated EOAs using the EIP-7702 delegation designator code prefix. (`packages/sdk/src/core/core.ts`, [packages/sdk/src/core/core.tsL369-R375](diffhunk://#diff-6567a6e87f732d8adba506b …

fix: enhance isContract method to check for delegated EOA
